# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SOFAIR
author: UMR SAS - INRAE - Institut Agro
logo: img/sofair-book.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - '*example_edr*'
    - '*csv_to_zarr*'
    - '*notebooks*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/geosas/sofair-book  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: img/icon.png
  use_issues_button: true
  use_repository_button: true
  extra_footer: <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr"><img alt="Creative Commons License" style="border-width:0" src="https://geosas.fr/sofair-book/_images/cc-by-sa.png" /></a> Ce travail est mis à disposition selon les termes de la Licence <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr">Creative Commons 4.0 International</a>.

sphinx:
  config:
    html_show_copyright: false

